### ISSUE TITLE
Error switching between SSG and SSR

### ISSUE THREAD

**Issue by erzr** [erzr/next-babel-conditional-ssg-ssr#1]
Currently if you switch the value that is passed to `nextModeBabelPlugin` you will receive an error when you go to build or export if the application was originally built in the other mode.

```
Error occurred prerendering page "/". Read more: https://err.sh/next.js/prerender-error
Error: Error for page /: pages with `getServerSideProps` can not be exported. See more info here: https://err.sh/next.js/gssp-export
    at Object.exportPage [as default] (C:\Code\ssrtest\node_modules\next\dist\export\worker.js:16:281)
info  - Exporting (2/2)
Error: Export encountered errors on following paths:
        /
    at exportApp (C:\Code\ssrtest\node_modules\next\dist\export\index.js:30:1103)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Deleting your `.next` build directory resolves this error. Explore if there's a better solution and if there is not a better way, update README.

**Comment by fivethreeo** [comment]
You somehow have to add the mode to webpacks cache version.

https://github.com/vercel/next.js/blob/canary/packages/next/build/webpack-config.ts#L1502
